language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
addons:
  ssh_known_hosts:
  - 132.232.184.158
before_install:
- openssl aes-256-cbc -K $encrypted_144fa57faf85_key -iv $encrypted_144fa57faf85_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@132.232.184.158 -o StrictHostKeyChecking=no 'cd ~/music && git pull && npm i -D'

